services:

  mysql:
    image: mysql:8.0
    container_name: hotel-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend

    container_name: hotel-backend
    restart: unless-stopped

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE_LENGTH: ${JWT_EXPIRE_LENGTH}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      SERVER_PORT: ${SERVER_PORT}

    ports:
      - "9192:9192"

    depends_on:
      mysql:
        condition: service_healthy


  frontend:
    build:
      context: ./frontend

    container_name: hotel-frontend
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend


volumes:
  mysql_data: