server:
  port: ${SERVER_PORT:9192}

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expire-length: ${JWT_EXPIRE_LENGTH:3600000}

app:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG