server:
  port: ${PORT:${SERVER_PORT:9192}}

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expire-length: ${JWT_EXPIRE_LENGTH:3600000}

app:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

logging:
  level:
    org.springframework.security: DEBUG